## Практическая работа №2 Линейная алгебра

In [24]:
import numpy as np

### Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


#### Решение

а) AB - перемножить нельзя. BA - перемножить нельзя
б) AB - 2x3. BA - перемножить нельзя
в) AB - 8x8. BA - 3x3
г) AB - 4x4. BA - 4x4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix}.$

### Решение

$A+B = \begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}$

$A+B = \begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix} * \begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}$

In [25]:
# проверяем
A = np.array([[1,-2],[3,0]])
B = np.array([[4,1],[0,5]])
print('A+B=',A+B)
print('AB=',A.dot(B))

A+B= [[ 5 -1]
 [ 3  5]]
AB= [[ 4 -9]
 [12  3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}.$

#### Решение

$3*\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix} - 2*\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix} + 4*\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix} =  \begin{pmatrix}
3+0+8 & 21-10-16\\
9-4+4 & -18+2+4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}$

In [26]:
# Проверка
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

#### Решение
$A^{T} = \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}$
<br>
$AA^{T} = \begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}*\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$
<br>
$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}*\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}$

In [27]:
A = np.array([[4,1],[5,-2],[2,3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [28]:
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [29]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

#### Решение

In [30]:
import random

class MatrixException(Exception):
    pass


class Matrix:
    """Класс матрицы."""
    def __init__(self, matrix):
        self.matrix = matrix
        self.rows = len(matrix)
        self.cols = len(matrix[0])

    def __str__(self):
        """
        Вывод матрицы
        :return:
        """
        return "\n".join([' '.join(map(str, tmp)) for tmp in self.matrix])

    def __add__(self, other):
        """
        Сложение матриц
        :param other: Другая матрица
        :return: Matrix
        """
        if self.rows != other.rows or self.cols != other.cols:
            raise MatrixException('Matrices has different size')
        # res = [map(sum, zip(*tmp)) for tmp in zip(self.matrix, other.matrix)]
        res = generate_matrix(self.rows, self.cols, nulls=True)
        for i in range(self.rows):
            for j in range(self.cols):
                res[i][j] = self.matrix[i][j] + other.matrix[i][j]
        return Matrix(res)

    def __mul__(self, other):
        """
        Умножение матриц
        :param other:
        :return: Matrix
        """
        res = []
        if self.cols !=  other.rows:
            raise MatrixException('Size error')
        for row in self.matrix:
            row_res = []
            for i in range(other.rows):
                res_val = 0
                for idx, v in enumerate(row):
                    res_val += v*other.matrix[idx][i]
                row_res.append(res_val)
            res.append(row_res  )
        return Matrix(res)


def generate_matrix(rows: int, cols: int, *, nulls: bool = False) -> list:
    """
    Генерация матриц
    :param rows: Строк
    :param cols: Столбцов
    :param nulls: Заполнить нулями
    :return: [[]]
    """
    matrix = []
    for i in range(rows):
        matrix.append([random.randint(0, 100) if not nulls else 0 for j in range(cols)])
    return matrix


A = Matrix(generate_matrix(3,3))
B = Matrix(generate_matrix(3,3))
print('A=',A)
print('B=',B)
print('AB')
print(A*B)

A= 28 2 84
6 52 56
16 95 72
B= 35 86 19
74 47 99
1 35 30
AB
1212 5442 3250
4114 4920 6942
7662 8361 11869


### Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\
cosx & sinx
\end{vmatrix};$$

   б)

$$\begin{vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end{vmatrix};$$

   в)

$$\begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix}.$$


#### Решение

а) $\begin{vmatrix}
sinx & -cosx\\
cosx & sinx
\end{vmatrix} = sin^2x+cos^2x = 1$
<br>
б) $\begin{vmatrix}
4 & 2 & 3\\
0 & 5 & 1\\
0 & 0 & 9
\end{vmatrix} = 4*(5*9-1*0)-2*(0*9-0*1)+3*(0*0-0*5) = 180$
в) $\begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{vmatrix} = 1*(5*9-8*6) - 2*(4*9-7*6) + 3*(4*8-7*5) = 0$

In [31]:
print('б)', np.linalg.det(np.array([[4,2,3],[0,5,1],[0,0,9]])))
print('в)', np.linalg.det(np.array([[1,2,3],[4,5,6],[7,8,9]])))

б) 180.0
в) 0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

   б) $det(A^{T})$;

   в) $det(2A)$.

#### Решение
   а) $det(A^{2}) = det(A)*det(A) = 4*4 = 16$;

   б) $det(A^{T}) = det(A) = 4$;

   в) $det(2A) = 2^n*det(A) = 2^n+2^2 = 2^{n+2}$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix}$$

вырожденная.

#### Решение
Матрица является вырожденной если ее определитель равен нулю
$det\begin{pmatrix}
-2 & 7 & -3\\
4 & -14 & 6\\
-3 & 7 & 13
\end{pmatrix} = -2(-14*13 - 7*6) - 7*(4*13 - 6*-3) + -3*(4*7-(-3)*(-14)) = 448 - 490 + 42 = 0$
доказали

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix}.$

### Решение
Будем использовать матод Гаусса для получения ступенчатой матрицы

а) $\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4
\end{pmatrix};$
Отнимем от 3й строки первую
$\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
1 & 1 & 1
\end{pmatrix};$
Строки 2 и 3 одинаковы можно выкинуть одну и поменяем местами строки 1 и 2
$\begin{pmatrix}
1 & 1 & 1\\
1 & 2 & 3
\end{pmatrix};$
Отнимем от второй строки первую
$\begin{pmatrix}
1 & 1 & 1\\
0 & 1 & 2
\end{pmatrix};$
типа того, ранг матрицы равен 2

#### Ответ: 2

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3\\
2 & 3 & 5 & 6
\end{pmatrix}$
Переместим первую строку наверх
$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 4 & 3
\end{pmatrix}.$
От второй строки отнимем четвертую
$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
0 & 0 & 2 & 2
\end{pmatrix}.$
Удалим дубль
$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
\end{pmatrix}.$
Отнимем от 2 3
$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\
0 & 0 & 0 & 1\\
\end{pmatrix}.$

#### Ответ: 3

In [32]:
print('а)', np.linalg.matrix_rank(np.array([
    [1, 2, 3],[1, 1, 1],[2, 3, 4]
])))
print('б)', np.linalg.matrix_rank(np.array([
[0, 0, 2, 1],
[0, 0, 2, 2],
[0, 0, 4, 3],
[2, 3, 5, 6]
])))

а) 2
б) 3
